export const Templates: TemplateCard[] = [
  {
    id: 1,
    imgUrl: "/templates/template-1.png",
    title: "E-Commerce",
    description: "Next.js Template for Businesses",
    link: "#",
    price: "Free",
  },
  {
    id: 2,
    imgUrl: "/templates/template-2.png",
    title: "Portfolio",
    description: "Next.js Template for Professionals",
    link: "#",
    price: "$ 50",
  },
  {
    id: 3,
    imgUrl: "/templates/template-3.png",
    title: "Recruitment",
    description: "Next.js Template for Recruiters",
    link: "#",
    price: "$ 50",
  },
  {
    id: 4,
    imgUrl: "/templates/template-4.png",
    title: "Photography",
    description: "Next.js Template for Photographers",
    link: "#",
    price: "$ 50",
  },
  {
    id: 5,
    imgUrl: "/templates/template-5.png",
    title: "Events",
    description: "Next.js Template for Events Organizers",
    link: "#",
    price: "$ 50",
  },
  {
    id: 6,
    imgUrl: "/templates/template-6.png",
    title: "Corporate",
    description: "Next.js Template for Corporate",
    link: "#",
    price: "$ 50",
  },
];
